---
docker_service_state: started
docker_service_enabled: true
docker_service_manage: true

docker_add_repo: true

docker_repo_url: https://download.docker.com/linux

docker_apt_repository: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable'
docker_apt_gpg_key: '{{ docker_repo_url }}/ubuntu/gpg'

docker_compose_version: 'v2.23.0'
docker_compose_arch: '{{ ansible_architecture }}'
docker_compose_url: 'https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-{{ docker_compose_arch }}'
docker_compose_path: /usr/local/bin/docker-compose
